packages:
  - src/libs/**

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - sharp

overrides:
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
