import fs from 'node:fs/promises';
import path from 'node:path';
import { _electron, expect, test } from '@playwright/test';
import { createFixtureHome, prepareAppWithStubbedData, setAppLanguage } from './support/e2e-fixture-runtime';
import { SAMPLE_PROJECTS } from './support/e2e-fixture-data';
import { getMainWindow } from './splashscreen/getMainWindow';

test('remembers a terminal choice and opens a stored project through the real main bridge', async ({}, testInfo) => {
    test.setTimeout(60000);
    const fixtureHome = await createFixtureHome();
    const targetId = process.platform === 'win32' ? 'command-prompt' : process.platform === 'darwin' ? 'macos-terminal' : 'gnome-terminal';
    const projectPath = path.join(fixtureHome, 'project é ; $HOME ` quote\'');
    await fs.mkdir(projectPath);
    const project = { ...SAMPLE_PROJECTS[0], path: projectPath };
    await fs.writeFile(path.join(fixtureHome, '.gd-launcher', 'projects.json'), JSON.stringify([project]));
    const env = Object.fromEntries(Object.entries(process.env).filter((entry): entry is [string, string] => typeof entry[1] === 'string'));
    delete env.ELECTRON_RUN_AS_NODE;
    const app = await _electron.launch({ args: ['.', `--user-data-dir=${path.join(fixtureHome, 'electron-user-data')}`], env: { ...env, GODOT_LAUNCHER_E2E_FIXTURES: '1', GODOT_LAUNCHER_E2E_HOME_DIR: fixtureHome } });
    try {
        const page = await getMainWindow(app);
        await setAppLanguage(page, 'English');
        await app.evaluate(async (_electron, { moduleUrl, targetId }) => {
            const target = globalThis as typeof globalThis & { __terminalLaunches?: string[]; __terminalAvailable?: boolean; __name?: (fn: unknown) => unknown };
            target.__name = (fn) => fn;
            target.__terminalLaunches = [];
            target.__terminalAvailable = true;
            const { TerminalAdapterService } = process.getBuiltinModule('module').createRequire(moduleUrl)(moduleUrl);
            TerminalAdapterService.prototype.discover = async () => target.__terminalAvailable ? [{ id: targetId, displayName: 'Fixture terminal', executablePath: '/fixture/terminal' }] : [];
            TerminalAdapterService.prototype.isAvailable = async () => true;
            TerminalAdapterService.prototype.launch = async (_candidate: unknown, directory: string) => { target.__terminalLaunches?.push(directory); return { success: true }; };
        }, { moduleUrl: path.resolve('dist-electron/tool-integration/integrations/terminal/terminal-adapter.service.js'), targetId });
        await prepareAppWithStubbedData(page, app, { projects: [project], toolIntegrations: [{ id: 'terminal', displayName: 'Terminal', status: 'available', executablePath: '/System/Applications/Utilities/Terminal.app', version: null }] });
        await page.getByTestId('btnSettings').click();
        await page.getByTestId('tabTools').click();
        await page.getByRole('button', { name: 'Edit Terminal' }).click();
        const drawer = page.getByRole('dialog', { name: 'Terminal settings' });
        await expect(drawer).toBeVisible();
        await drawer.getByRole('button', { name: 'Rescan', exact: true }).click();
        await drawer.getByRole('radio', { name: /Fixture terminal/ }).click();
        await expect(drawer.getByRole('radio', { name: /Fixture terminal/ })).toBeChecked();
        const stored = JSON.parse(await fs.readFile(path.join(fixtureHome, '.gd-launcher', 'tool-integrations.json'), 'utf8'));
        expect(stored.tools.terminal.configuration.preferences[process.platform]).toBe(targetId);
        await page.screenshot({ path: testInfo.outputPath('terminal-settings.png') });
        await page.keyboard.press('Escape');
        await page.getByTestId('btnProjects').click();
        await page.getByTestId('btnProjectTerminal').first().hover();
        await expect(page.getByRole('tooltip')).toHaveText('Open Terminal Here');
        await page.screenshot({ path: testInfo.outputPath('project-terminal-quick-action.png') });
        await page.getByRole('button', { name: 'Open Terminal Here', exact: true }).click();
        await expect.poll(() => app.evaluate(() => (globalThis as typeof globalThis & { __terminalLaunches?: string[] }).__terminalLaunches)).toEqual([projectPath]);
        await page.getByTestId('tabProjectList').click();
        await page.getByRole('button', { name: 'Open Terminal Here', exact: true }).click();
        await expect.poll(() => app.evaluate(() => (globalThis as typeof globalThis & { __terminalLaunches?: string[] }).__terminalLaunches)).toEqual([projectPath, projectPath]);
        await page.getByTestId('btnSettings').click();
        await page.getByTestId('tabTools').click();
        await page.getByRole('button', { name: 'Edit Terminal' }).click();
        await expect(drawer.getByRole('radio', { name: /Fixture terminal/ })).toBeChecked();
        await drawer.getByLabel('Enable terminal for project folders').click();
        await expect(drawer.getByLabel('Enable terminal for project folders')).not.toBeChecked();
        await expect(drawer.getByText('Disabled', { exact: true })).toBeVisible();
        await expect(drawer.getByText('No supported terminal is currently available.')).toHaveCount(0);
        await expect(drawer.getByRole('alert')).toHaveCount(0);
        await drawer.getByRole('button', { name: 'Rescan', exact: true }).click();
        await expect(drawer.getByText('Disabled', { exact: true })).toBeVisible();
        await page.keyboard.press('Escape');
        await page.getByTestId('btnProjects').click();
        await page.getByRole('button', { name: 'Open Terminal Here', exact: true }).click();
        await expect(page.getByText('Terminal is disabled. Enable it in Settings > Tools > Terminal.')).toBeVisible();
        await page.getByRole('button', { name: 'Ok', exact: true }).click();
        await page.getByTestId('btnSettings').click();
        await page.getByTestId('tabTools').click();
        await page.getByRole('button', { name: 'Edit Terminal' }).click();
        await drawer.getByLabel('Enable terminal for project folders').click();
        await expect(drawer.getByLabel('Enable terminal for project folders')).toBeChecked();
        await app.evaluate(() => { (globalThis as typeof globalThis & { __terminalAvailable?: boolean }).__terminalAvailable = false; });
        await drawer.getByRole('button', { name: 'Rescan', exact: true }).click();
        await expect(drawer.getByText(`${targetId} is no longer available. Rescan or choose another terminal.`)).toBeVisible();
        await expect(drawer.getByRole('radio', { name: 'Automatic', exact: true })).not.toBeChecked();
        await expect.poll(() => app.evaluate(() => (globalThis as typeof globalThis & { __terminalLaunches?: string[] }).__terminalLaunches)).toEqual([projectPath, projectPath]);
    } finally {
        await app.close();
        await fs.rm(fixtureHome, { recursive: true, force: true });
    }
});
