name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
      - release/**

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: Sync npm version
        run: npm install --global npm@11.16.0

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run lint
      - name: Run lint
        run: npx biome check --reporter summary

      # Run build:sources
      - name: Run build:sources
        run: npm run build:sources
        
      # Run Unit tests
      - name: Run Unit tests
        run: npm run test:unit
      

      
